package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatorVersion = "openapi-operations/v1"

type operation struct {
	OperationID string `yaml:"operationId"`
}

type document struct {
	Paths map[string]map[string]operation `yaml:"paths"`
}

func main() {
	specPath := flag.String("spec", "openapi.yaml", "OpenAPI document")
	outputPath := flag.String("output", "testdata/openapi-v0.9.4-operations.txt", "generated manifest")
	check := flag.Bool("check", false, "fail when the generated manifest differs")
	flag.Parse()

	raw, err := os.ReadFile(*specPath)
	fail(err)
	var spec document
	fail(yaml.Unmarshal(raw, &spec))

	methods := map[string]bool{
		"get": true, "head": true, "post": true, "put": true,
		"patch": true, "delete": true,
	}
	var lines []string
	for path, item := range spec.Paths {
		for method, op := range item {
			if !methods[method] || op.OperationID == "" {
				continue
			}
			lines = append(lines, op.OperationID+"\t"+strings.ToUpper(method)+"\t"+path)
		}
	}
	sort.Strings(lines)
	generated := []byte("# Code generated by " + generatorVersion + "; DO NOT EDIT.\n" +
		strings.Join(lines, "\n") + "\n")

	if *check {
		current, readErr := os.ReadFile(*outputPath)
		fail(readErr)
		if !bytes.Equal(current, generated) {
			fmt.Fprintf(os.Stderr, "%s is stale; run make openapi-generate\n", *outputPath)
			os.Exit(1)
		}
		return
	}
	// This is a checked-in, non-sensitive generated contract manifest and must
	// remain readable by repository tooling regardless of the generating user.
	fail(os.WriteFile(*outputPath, generated, 0o644)) //nolint:gosec
}

func fail(err error) {
	if err == nil {
		return
	}
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
